runtime: nodejs
env: flex

env_variables:
  ORDERS_HOST: "https://geoawareness.woolpert.dev"

# Keep it small and cheap
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10